- name: Clone Source
        run: |
          cd $GITHUB_WORKSPACE/work
          # Menambah --recursive untuk memastikan sub-modul terbawa
          git clone --recursive https://github.com/amirarjenso2003-dot/Xiaomi_Kernel_OpenSource-reboot-9aosp android-kernel --depth=1

      - name: Build Kernel (Clean Baseline)
        run: |
          cd $GITHUB_WORKSPACE/work/android-kernel
          # Cek isi folder untuk memastikan Makefile ada
          ls -a
          
          export PATH=$GITHUB_WORKSPACE/work/clang/bin:$GITHUB_WORKSPACE/work/gcc64/bin:$GITHUB_WORKSPACE/work/gcc32/bin:$PATH
          
          # Gunakan perintah sed hanya jika Makefile ditemukan
          if [ -f Makefile ]; then
            sed -i 's/^KBUILD_CFLAGS   :=/KBUILD_CFLAGS   := -fno-builtin-stpcpy -fno-builtin-strcpy /' Makefile
          fi
          
          make O=out ARCH=arm64 clean
          make O=out ARCH=arm64 mrproper
          # ... sisa perintah make lainnya tetap sama
